name: Unit tests
on: [ pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Go test
    env:
      SILENT: true
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '1.17'
      - name: Go test
        run: make test
      - name: Go e2e test
        run: make e2e
  fuzz:
    runs-on: ubuntu-latest
    name: Go fuzz test
    env:
      SILENT: true
      FUZZ: true
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '1.17'
      - name: Go fuzz test
        timeout-minutes: 10
        run: make fuzz