name: Property tests
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Run tests
        run: make property-tests
      - name: Archive test logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: property-logs
          path: property-logs-*/
